# Generated by Django 5.1.6 on 2025-04-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_course_created_at_course_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
