name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env: #
      GITHUB_ACTIONS: true

    steps:
      - name: Check out code # allow us to clone code to container where we gonna do jobs
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        # flag --no-root for DO NOT install the project itself as a package.
        run: |
          poetry install --no-root
        #poetry run runs any command inside the virtual environment that Poetry creates.
        #Without this, the command is executed "as is" — and there is no Django.

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV

      - name: Run migrate
        run: poetry run python manage.py migrate

      - name: Run tests
        run: poetry run python manage.py test